#服务器上的的上传文件存放地址
web:
  image-path: /cnctwhale/whaleapp/showimgs

#默认使用配置
spring:
  datasource:
      #服务器数据库
      url: jdbc:mysql://47.107.69.159:3306/whale?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: cnct123456
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initialSize: 3
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 600000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 3000000

## Redis 配置
## Redis数据库索引（默认为0）
#spring.redis.database: 2
## Redis服务器地址
#spring.redis.host: 118.190.163.217
#spring.redis.host: 127.0.0.1
## Redis服务器连接端口
#spring.redis.port: 6388
#spring.redis.port: 6379
## Redis服务器连接密码（默认为空）
#spring.redis.password: cnct_redis217
#spring.redis.password:
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active: 8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait: -1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle: 8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle: 0
## 连接超时时间（毫秒）
#spring.redis.timeout: 0